
package com.maxelyz.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVoiceConvert", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVoiceConvert {


    /**
     * 
     * @param trackId
     * @param date
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConvertVoice", action = "http://tempuri.org/IVoiceConvert/ConvertVoice")
    @WebResult(name = "ConvertVoiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConvertVoice", targetNamespace = "http://tempuri.org/", className = "com.maxelyz.webservice.ConvertVoice")
    @ResponseWrapper(localName = "ConvertVoiceResponse", targetNamespace = "http://tempuri.org/", className = "com.maxelyz.webservice.ConvertVoiceResponse")
    public String convertVoice(
        @WebParam(name = "track_id", targetNamespace = "http://tempuri.org/")
        Integer trackId,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date);

    /**
     * 
     * @param trackId
     * @param date
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMp3DownloadLink", action = "http://tempuri.org/IVoiceConvert/GetMp3DownloadLink")
    @WebResult(name = "GetMp3DownloadLinkResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMp3DownloadLink", targetNamespace = "http://tempuri.org/", className = "com.maxelyz.webservice.GetMp3DownloadLink")
    @ResponseWrapper(localName = "GetMp3DownloadLinkResponse", targetNamespace = "http://tempuri.org/", className = "com.maxelyz.webservice.GetMp3DownloadLinkResponse")
    public String getMp3DownloadLink(
        @WebParam(name = "track_id", targetNamespace = "http://tempuri.org/")
        Integer trackId,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date);

}
