
package com.maxelyz.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VoiceConvert", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.50.65:83/VoiceConvert.svc?wsdl")
public class VoiceConvert
    extends Service
{

    private final static URL VOICECONVERT_WSDL_LOCATION;
    private final static WebServiceException VOICECONVERT_EXCEPTION;
    private final static QName VOICECONVERT_QNAME = new QName("http://tempuri.org/", "VoiceConvert");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.50.65:83/VoiceConvert.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VOICECONVERT_WSDL_LOCATION = url;
        VOICECONVERT_EXCEPTION = e;
    }

    public VoiceConvert() {
        super(__getWsdlLocation(), VOICECONVERT_QNAME);
    }

    public VoiceConvert(WebServiceFeature... features) {
        super(__getWsdlLocation(), VOICECONVERT_QNAME, features);
    }

    public VoiceConvert(URL wsdlLocation) {
        super(wsdlLocation, VOICECONVERT_QNAME);
    }

    public VoiceConvert(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VOICECONVERT_QNAME, features);
    }

    public VoiceConvert(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VoiceConvert(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IVoiceConvert
     */
    @WebEndpoint(name = "BasicHttpBinding_IVoiceConvert")
    public IVoiceConvert getBasicHttpBindingIVoiceConvert() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IVoiceConvert"), IVoiceConvert.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVoiceConvert
     */
    @WebEndpoint(name = "BasicHttpBinding_IVoiceConvert")
    public IVoiceConvert getBasicHttpBindingIVoiceConvert(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IVoiceConvert"), IVoiceConvert.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VOICECONVERT_EXCEPTION!= null) {
            throw VOICECONVERT_EXCEPTION;
        }
        return VOICECONVERT_WSDL_LOCATION;
    }

}
