
package com.maxelyz.webservicevoice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExportVoiceAspect", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.51.30:100/ExportVoiceAspect.svc?wsdl")
public class ExportVoiceAspect
    extends Service
{

    private final static URL EXPORTVOICEASPECT_WSDL_LOCATION;
    private final static WebServiceException EXPORTVOICEASPECT_EXCEPTION;
    private final static QName EXPORTVOICEASPECT_QNAME = new QName("http://tempuri.org/", "ExportVoiceAspect");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.51.30:100/ExportVoiceAspect.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXPORTVOICEASPECT_WSDL_LOCATION = url;
        EXPORTVOICEASPECT_EXCEPTION = e;
    }

    public ExportVoiceAspect() {
        super(__getWsdlLocation(), EXPORTVOICEASPECT_QNAME);
    }

    public ExportVoiceAspect(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXPORTVOICEASPECT_QNAME, features);
    }

    public ExportVoiceAspect(URL wsdlLocation) {
        super(wsdlLocation, EXPORTVOICEASPECT_QNAME);
    }

    public ExportVoiceAspect(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXPORTVOICEASPECT_QNAME, features);
    }

    public ExportVoiceAspect(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExportVoiceAspect(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IExportVoiceAspect
     */
    @WebEndpoint(name = "BasicHttpBinding_IExportVoiceAspect")
    public IExportVoiceAspect getBasicHttpBindingIExportVoiceAspect() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IExportVoiceAspect"), IExportVoiceAspect.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExportVoiceAspect
     */
    @WebEndpoint(name = "BasicHttpBinding_IExportVoiceAspect")
    public IExportVoiceAspect getBasicHttpBindingIExportVoiceAspect(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IExportVoiceAspect"), IExportVoiceAspect.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXPORTVOICEASPECT_EXCEPTION!= null) {
            throw EXPORTVOICEASPECT_EXCEPTION;
        }
        return EXPORTVOICEASPECT_WSDL_LOCATION;
    }

}
